name: CatHP
version: '1.0'
main: org.jestos.catHP.CatHP
depend:
  - Vault
api-version: '1.21'
commands:
  cat-hp:
    usage: "/cat-hp"
    aliases: [chp, hp]
permissions:
  cat-hp.reload:
    description: "Allows using the reload command"
    default: false
  cat-hp.buy:
    description: "Allows using the buy command"
    default: false
  cat-hp.resetbuy:
    description: "Allows resetting the buy price for a player"
    default: false
  cat-hp.set:
    description: "Allows setting a player's HP"
    default: false
  cat-hp.reset:
    description: "Allows resetting a player's HP"
    default: false
  cat-hp.info:
    description: "Allows using the info command"
    default: false
  role.admin:
    description: "Admin role with all permissions"
    default: op
    children:
      cat-hp.reload: true
      cat-hp.buy: true
      cat-hp.resetbuy: true
      cat-hp.set: true
      cat-hp.reset: true
      cat-hp.info: true